# Generated by Django 4.0.1 on 2022-02-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('VehicleId', models.AutoField(primary_key=True, serialize=False)),
                ('VehicleName', models.CharField(max_length=100)),
                ('VehicleType', models.CharField(max_length=100)),
                ('VehicleMake', models.CharField(max_length=100)),
                ('VehicleModel', models.CharField(max_length=100)),
                ('VehicleColor', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('EmployeeVehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.vehicles')),
            ],
        ),
    ]
