# Generated by Django 4.0.1 on 2022-01-30 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('DepartmentId', models.AutoField(primary_key=True, serialize=False)),
                ('DepartmentName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('EmployeeId', models.AutoField(primary_key=True, serialize=False)),
                ('EmployeeName', models.CharField(max_length=100)),
                ('Department', models.CharField(max_length=100)),
                ('DateOfJoining', models.DateField()),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('VehicleId', models.CharField(max_length=18, primary_key=True, serialize=False)),
                ('VehicleName', models.CharField(max_length=100)),
                ('VehicleMake', models.CharField(max_length=100)),
                ('VehicleModel', models.CharField(max_length=100)),
                ('VehiclePlate', models.CharField(max_length=100)),
                ('VehicleYear', models.CharField(max_length=100)),
                ('PhotoFileName', models.CharField(max_length=100)),
            ],
        ),
    ]
