# Generated by Django 4.0.1 on 2022-02-08 17:21

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departments',
            fields=[
                ('department_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('department_name', models.CharField(max_length=100)),
                ('department_manager', models.CharField(max_length=100)),
                ('department_location', models.CharField(max_length=100)),
                ('department_phone', models.CharField(max_length=100)),
                ('department_email', models.EmailField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicles',
            fields=[
                ('vehicle_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('vehicle_name', models.CharField(max_length=100)),
                ('vehicle_type', models.CharField(max_length=100)),
                ('vehicle_make', models.CharField(max_length=100)),
                ('vehicle_model', models.CharField(max_length=100)),
                ('vehicle_year', models.CharField(max_length=100)),
                ('vehicle_color', models.CharField(max_length=100)),
                ('vehicle_license', models.CharField(max_length=100)),
                ('vehicle_vin', models.CharField(max_length=100)),
                ('vehicle_license_plate', models.CharField(max_length=100)),
                ('vehicle_documents', models.FileField(upload_to='vehicle_documents/')),
            ],
        ),
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('employee_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('employee_first_name', models.CharField(max_length=100)),
                ('employee_last_name', models.CharField(max_length=100)),
                ('employee_dob', models.DateField()),
                ('employee_ssn', models.CharField(max_length=100)),
                ('employee_address', models.CharField(max_length=100)),
                ('employee_email', models.EmailField(max_length=100)),
                ('employee_phone', models.CharField(max_length=100)),
                ('employee_hire_date', models.DateField()),
                ('employee_position', models.CharField(max_length=100)),
                ('employee_license', models.CharField(max_length=100)),
                ('employee_license_state', models.CharField(max_length=100)),
                ('employee_license_number', models.CharField(max_length=100)),
                ('employee_license_expiration', models.DateField()),
                ('employe_documents', models.FileField(upload_to='employee_documents/')),
                ('employee_department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.departments')),
                ('employee_vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='EmployeeApp.vehicles')),
            ],
        ),
    ]
